const linksData = [{
    mainTitle:'Popular Real Estate Markets',
    menuContent:[
                {title:"Washington Real Estate",herfLink:'/'},
                {title:"Chicago Real Estate",herfLink:'/'},
                {title:"Dallas Real Estate",herfLink:'/'},
                {title:"Fort Worth Real",herfLink:'/'},
                {title:"Houston Real Estate",herfLink:'/'},
                {title:"Senior Housing",herfLink:'/'},
                {title:"Los Angeles Real Estate",herfLink:'/'},
                {title:"Atlanta Real Estate",herfLink:'/'},
                {title:"Phoenix Real Estate",herfLink:'/'},
                {title:"Boston Real Estate",herfLink:'/'},
                {title:"Miami Real Estate",herfLink:'/'},
                {title:"Orlando FL Real Estate",herfLink:'/'},
                {title:"San Diego Real Estate",herfLink:'/'},
                {title:"Tampa Real Estate",herfLink:'/'},
                {title:"Las Vegas Real Estate",herfLink:'/'},
                {title:"West Palm Beach Real Estate",herfLink:'/'},
                {title:"Raleigh Real Estate",herfLink:'/'},
                {title:"New Haven Real Estate",herfLink:'/'},
                {title:"Durham Real Estate",herfLink:'/'},
                {title:"Chapel Hill Real Estate",herfLink:'/'},
                {title:"Saint Petersburg FL Real Estate",herfLink:'/'},
                {title:"Charlotte Real Estate",herfLink:'/'},
                {title:"Denver Real Estate",herfLink:'/'},
                {title:"New York City Real Estate",herfLink:'/'},
                {title:"Staten Island NY Real Estate",herfLink:'/'},
                {title:"Brooklyn NY Real Estate",herfLink:'/'},
                {title:"Queens NY Real Estate",herfLink:'/'},
                {title:"Bronx NY Real Estate",herfLink:'/'},
                {title:"Manhattan NY Real Estate",herfLink:'/'},
                {title:"New York State Real Estate",herfLink:'/'},
                {title:"Philadelphia PA Real Estate",herfLink:'/'},
                {title:"Sacramento Real Estate",herfLink:'/'},
                {title:"Saint Louis Real Estate",herfLink:'/'},
                {title:"Seattle Real Estate",herfLink:'/'},
                {title:"San Francisco Real Estate",herfLink:'/'},
                {title:"Austin TX Real Estate",herfLink:'/'},
                {title:"Jacksonville FL Real Estate",herfLink:'/'},
                {title:"Plano Real Estate",herfLink:'/'},
                {title:"San Jose CA Real Estate",herfLink:'/'},
                {title:"Seattle WA Real Estate",herfLink:'/'},
]},{
    mainTitle:'Popular Real ',
    menuContent:[
                {title:"Homes For Sale Near Universities",herfLink:'/'},
                {title:"Local Real Estate Market",herfLink:'/'},
                {title:"Real Estate Mobile Apps",herfLink:'/'},
                {title:"Android Rentals App",herfLink:'/'},
                {title:"iPhone Rentals App",herfLink:'/'},
                {title:"Full-Service Movers",herfLink:'/'},
                {title:"Moving Company Search on Moving.com",herfLink:'/'},
                {title:"Truck Rental",herfLink:'/'},
                {title:"Assisted Living on SeniorHousingNet.com",herfLink:'/'},
                {title:"Real Estate Search",herfLink:'/'},
                {title:"New Home Construction Search",herfLink:'/'},
                {title:"Foreclosure Search",herfLink:'/'},
                {title:"Recently Sold Homes Search",herfLink:'/'},
                {title:"Property Record Search",herfLink:'/'},
                {title:"Apartment Rental Search",herfLink:'/'},
                {title:"iPhone Real Estate App",herfLink:'/'},
                {title:"Android Real Estate App",herfLink:'/'},
]},{
        mainTitle:'Popular Resources',
        menuContent:[
            {title:"Washington Real Estate",herfLink:'/'},
            {title:"Chicago Real Estate",herfLink:'/'},
            {title:"Dallas Real Estate",herfLink:'/'},
            {title:"Fort Worth Real",herfLink:'/'},
            {title:"Houston Real Estate",herfLink:'/'},
            {title:"Senior Housing",herfLink:'/'},
            {title:"Los Angeles Real Estate",herfLink:'/'},
            {title:"Atlanta Real Estate",herfLink:'/'},
            {title:"Phoenix Real Estate",herfLink:'/'},
            {title:"Boston Real Estate",herfLink:'/'},
            {title:"Miami Real Estate",herfLink:'/'},
            {title:"Orlando FL Real Estate",herfLink:'/'},
            {title:"San Diego Real Estate",herfLink:'/'},
            {title:"Tampa Real Estate",herfLink:'/'},
            {title:"Las Vegas Real Estate",herfLink:'/'},
            {title:"West Palm Beach Real Estate",herfLink:'/'},
            {title:"Raleigh Real Estate",herfLink:'/'},
            {title:"New Haven Real Estate",herfLink:'/'},
            {title:"Durham Real Estate",herfLink:'/'},
            {title:"Chapel Hill Real Estate",herfLink:'/'},
            {title:"Saint Petersburg FL Real Estate",herfLink:'/'},
            {title:"Charlotte Real Estate",herfLink:'/'},
            {title:"Denver Real Estate",herfLink:'/'},
            {title:"New York City Real Estate",herfLink:'/'},
            {title:"Staten Island NY Real Estate",herfLink:'/'},
            {title:"Brooklyn NY Real Estate",herfLink:'/'},
            {title:"Queens NY Real Estate",herfLink:'/'},
            {title:"Bronx NY Real Estate",herfLink:'/'},
            {title:"Manhattan NY Real Estate",herfLink:'/'},
            {title:"New York State Real Estate",herfLink:'/'},
            {title:"Philadelphia PA Real Estate",herfLink:'/'},
            {title:"Sacramento Real Estate",herfLink:'/'},
            {title:"Saint Louis Real Estate",herfLink:'/'},
            {title:"Seattle Real Estate",herfLink:'/'},
            {title:"San Francisco Real Estate",herfLink:'/'},
            {title:"Austin TX Real Estate",herfLink:'/'},
            {title:"Jacksonville FL Real Estate",herfLink:'/'},
            {title:"Plano Real Estate",herfLink:'/'},
            {title:"San Jose CA Real Estate",herfLink:'/'},
            {title:"Seattle WA Real Estate",herfLink:'/'},
]},{
        mainTitle:'US Real Estate Overview & Homes for Sale',
        menuContent:[
                    {title:"Alabama Real Estate Overview",herfLink:'/'},
                    {title:"Alaska Real Estate Overview",herfLink:'/'},
                    {title:"Arizona Real Estate Overview",herfLink:'/'},
                    {title:"Arkansas Real Estate Overview",herfLink:'/'},
                    {title:"California Real Estate Overview",herfLink:'/'},
                    {title:"Colorado Real Estate Overview",herfLink:'/'},
                    {title:"Connecticut Real Estate Overview",herfLink:'/'},
                    {title:"Delaware Real Estate Overview",herfLink:'/'},
                    {title:"District of Columbia Real Estate Overview",herfLink:'/'},
                    {title:"Florida Real Estate Overview",herfLink:'/'},
                    {title:"Georgia Real Estate Overview",herfLink:'/'},
                    {title:"Hawaii Real Estate Overview",herfLink:'/'},
                    {title:"San Diego Real Estate",herfLink:'/'},
                    {title:"Tampa Real Estate",herfLink:'/'},
                    {title:"Las Vegas Real Estate",herfLink:'/'},
                    {title:">West Palm Beach Real Estate",herfLink:'/'},
                    {title:">Raleigh Real Estate",herfLink:'/'},
                    {title:"New Haven Real Estate",herfLink:'/'},
                    {title:">Durham Real Estate",herfLink:'/'},
                    {title:"Chapel Hill Real Estate",herfLink:'/'},
                    {title:"Saint Petersburg FL Real Estate",herfLink:'/'},
                    {title:"Charlotte Real Estate",herfLink:'/'},
                    {title:"Denver Real Estate",herfLink:'/'},
                    {title:"New York City Real Estate",herfLink:'/'},
                    {title:"Staten Island NY Real Estate",herfLink:'/'},
                    {title:"Brooklyn NY Real Estate",herfLink:'/'},
                    {title:"Queens NY Real Estate",herfLink:'/'},
                    {title:"Bronx NY Real Estate",herfLink:'/'},
                    {title:"Manhattan NY Real Estate",herfLink:'/'},
                    {title:"New York State Real Estate",herfLink:'/'},
                    {title:"Philadelphia PA Real Estate",herfLink:'/'},
                    {title:"Sacramento Real Estate",herfLink:'/'},
                    {title:"Saint Louis Real Estate",herfLink:'/'},
                    {title:"Seattle Real Estate",herfLink:'/'},
                    {title:"San Francisco Real Estate",herfLink:'/'},
                    {title:"Austin TX Real Estate",herfLink:'/'},
                    {title:"Jacksonville FL Real Estate",herfLink:'/'},
                    {title:"Plano Real Estate",herfLink:'/'},
                    {title:"San Jose CA Real Estate",herfLink:'/'},
                    {title:"Seattle WA Real Estate",herfLink:'/'},
        ]}
];
export {linksData};
